# CLIP with Learnable Temperature Configuration
experiment_name: "clip_learnable_temp"
output_dir: "results"
device: "auto"
seed: 42

# Data paths
data:
  train_image_embeddings: "train_image_embeddings.pt"
  train_text_embeddings: "train_text_embeddings.pt"
  val_image_embeddings: "val_image_embeddings.pt"
  val_text_embeddings: "val_text_embeddings.pt"
  test_image_embeddings: "test_image_embeddings.pt"
  test_text_embeddings: "test_text_embeddings.pt"

# Model architecture
model:
  type: "clip"
  output_dim: 512
  hidden_dim: 1024
  dropout: 0.1
  learnable_temp: true

# Training settings
training:
  batch_size: 1024
  learning_rate: 1e-4
  weight_decay: 0.01
  num_epochs: 50
  patience: 5
  max_grad_norm: 1.0

# Loss function
loss:
  type: "clip"
  temperature: 0.07  # Initial temperature (will be learned)

# Evaluation settings
evaluation:
  top_k: [1, 5, 10, 50]
  visualization_samples: 5000
  tsne_perplexity: 30
  save_features: true