base_data_dir: "../pretrain_encoded"
data:
  test_image_embeddings: test_image_embeddings.pt
  test_text_embeddings: test_text_embeddings.pt
  test_metadata: test_metadata.json
  train_image_embeddings: train_image_embeddings.pt
  train_text_embeddings: train_text_embeddings.pt
  train_metadata: train_metadata.json
  val_image_embeddings: val_image_embeddings.pt
  val_text_embeddings: val_text_embeddings.pt
  val_metadata: val2017_metadata.json
device: auto
evaluation:
  save_features: true
  top_k:
  - 1
  - 5
  - 10
  - 50
  tsne_perplexity: 30
  visualization_samples: 5000
experiment_name: optuna_best_v2
loss:
  temperature: 0.039441932181046746
  type: softmax_infonce
model:
  dropout: 0.11707560106448871
  hidden_dim: 1024
  num_heads: 8
  num_layers: 1
  output_dim: 1024
  type: attention
output_dir: results
seed: 42
training:
  batch_size: 4096
  learning_rate: 0.00016121633185973413
  max_grad_norm: 1.0
  num_epochs: 50
  patience: 5
  weight_decay: 0.013347206253055587