# Queue-based InfoNCE Configuration with Hard Negatives
experiment_name: "queue_infonce_baseline"
output_dir: "results"
device: "auto"
seed: 42

# Data paths
data:
  train_image_embeddings: "train_image_embeddings.pt"
  train_text_embeddings: "train_text_embeddings.pt"
  val_image_embeddings: "val_image_embeddings.pt"
  val_text_embeddings: "val_text_embeddings.pt"
  test_image_embeddings: "test_image_embeddings.pt"
  test_text_embeddings: "test_text_embeddings.pt"

# Model architecture
model:
  type: "attention"
  output_dim: 512
  hidden_dim: 1024
  num_heads: 8
  num_layers: 2
  dropout: 0.1

# Training settings
training:
  batch_size: 512  # Smaller batch for queue losses
  learning_rate: 1e-4
  weight_decay: 0.01
  num_epochs: 50
  patience: 5
  max_grad_norm: 1.0

# Loss function
loss:
  type: "queue_infonce"
  temperature: 0.07
  queue_size: 4096
  feature_dim: 512

# Evaluation settings
evaluation:
  top_k: [1, 5, 10, 50]
  visualization_samples: 5000
  tsne_perplexity: 30
  save_features: true