# Quick Test Configuration (for debugging/prototyping)

experiment_name: "quick_test"
output_dir: "results"
device: "auto"
seed: 42

data:
  train_image_embeddings: "../pretrain_encoded/train_image_embeddings.pt"
  train_text_embeddings: "../pretrain_encoded/train_text_embeddings.pt"
  val_image_embeddings: "../pretrain_encoded/val_image_embeddings.pt"
  val_text_embeddings: "../pretrain_encoded/val_text_embeddings.pt"
  test_image_embeddings: "../pretrain_encoded/test_image_embeddings.pt"
  test_text_embeddings: "../pretrain_encoded/test_text_embeddings.pt"

model:
  type: "mlp"
  output_dim: 256
  hidden_dim: 512
  dropout: 0.1

training:
  batch_size: 1024
  learning_rate: 1e-3
  weight_decay: 0.01
  num_epochs: 10
  patience: 3
  max_grad_norm: 1.0

loss:
  type: "siglip"
  temperature: 0.05

evaluation:
  top_k: [1, 5, 10]
  visualization_samples: 1000
  tsne_perplexity: 20
  save_features: false